### ISSUE TITLE
Track first iteration fork efforts

### ISSUE THREAD

**Issue by ivangsa** [ivangsa/karate-ide#1]
This project started as a fork from original [karate-runner](https://github.com/kirksl/karate-runner) extension.

We would like to make this extension a one stop and our primary tool for: 

a) Rest APIs manual testing and debug leveraging already existing karate scripts 
b) Karate scripts development 

adding it some functionality that we are missing from other tools like postman, chrome devtools or intellij...

Checklist

- [x] Karate.env switcher
- [x] Focus/Filter features/scenarios and test-data files using glob regexps and karate tags
- [x] EventLogs Server listening from events send by a karate RuntimeHook with karate runtime information that will feed:
- [x] Structured http logs viewer using a tree view (v1)
  - [ ] Click to open request/response payloads in empty json document
  - [ ] Tree view (v2) with scenarios calls hierarchy
  - [ ] Click to open feature line where http calls are made
  - [ ] JsonPath filter command for opened payload json documents
- [x] Excutions view:
  - [x] Replay last execution
  - [x] Play single scenario from last execution
  - [x] Click to open scenario from executions tree
- [ ] Explore a way to keep _session variables_ between manual executions (like authentication sessions or response output)
- [x] Karate feature code generation from OpenAPI definition command
- [x] Refactor launch/debug auto-configuration: don't try to guess build system or depend on configured default terminal to work.

After we have completed these and other features we may join forces again with original upstream project.

![image](https://user-images.githubusercontent.com/1246876/103078879-13f26200-45d3-11eb-9ddf-cf708902e9f6.png)

**Comment by kirksl** [comment]
@ivangsa great ideas!  i'd like to work with you and ensure the main project/vscode marketplace extension for karate runner are updated and we don't start diverging with multiple projects available.  let's discuss when you have time.  below are some thoughts i have.

- [ ] Karate.env switcher.
i've thought about this in the past and think this would be easy to implement.  if specified in the UI the maven/gradle command builder can simply pick that value and set karate.env=<value>

- [ ] Focus/Filter features/scenarios/data files.
i assume you are talking about the Tests View in the Karate Activity?  i'd like to do this too as it gets difficult to find tests as project increases in size.

- [ ] EventLogs Server listening from events send by a karate RuntimeHook.
is this ticket part of the http logs viewer effort? https://github.com/kirksl/karate-runner/pull/74
really like the idea around all of this.  are you aware of the current replay option by viewing results in the status bar?  what are your thoughts with that?  seems like the execution view might create duplicity and one would not be needed.

- [ ] Explore a way to keep session variables between manual executions
can you explain the use cases around this?  trying to understand the usefulness of it.

- [ ] Karate feature code generation from OpenAPI
we explored this and were avoiding it at the time due to the overhead to ensure the extension stays in sync with the open api standard and supporting multiple standards.  what are your thoughts about that and do you see a way to implement this with low overhead?

- [ ] Refactor launch/debug auto-configuration
i've thought about this in the past.  also easy to implement.  really just need need to detect if jar, maven, gradle internally and build the command.  this was a low priority as most users one build system.  definitely something we want to do though to streamline user management though.

**Comment by ivangsa** [comment]
hi @kirksl

let me tell you about what is broken in current extension and what we want to have:

First the **"Karate Run" functionality is broken** on windows because it never builds a command line that works on windows
- On windows, it relies on cmd being de default terminal in vscode :-( which nobody in <del>their right mind</del> our team uses, so it doesn't work at all for us
- Also "Autodetecting" doesn't give use any power to fix it unless we drop a karate.jar on the root of the project..

And these two things **renders "Karate Tests" view useless because** every time you click an scenario this happens

![image](https://user-images.githubusercontent.com/1246876/103142581-a85ce180-4705-11eb-9315-fa7e1d642f41.png)


### Second:  debugging API tests by copy/pasting output strings from terminal logs is very inefficient. 
And in debug view, variables are also test strings, we have fixed that in karate-core for next version, but still was missing..

Our team is crying out loud about these copy/pasting limitation.
We came from using to other tools like postman, insomnia or chrome devtools where structured json views are taken for granted.

![image](https://user-images.githubusercontent.com/1246876/103142641-b65f3200-4706-11eb-90f9-70915a23de93.png)

### Something like this is what we want instead
![image](https://user-images.githubusercontent.com/1246876/103142646-dc84d200-4706-11eb-989f-e7efce67a863.png)

Also **people coming from IntelliJ are missing the executions view** where they can relaunch a single test or all of them or just open it. It's also important being able to identify and relaunch a failing test quickly. (See above)


Other things like:

- Session variables between executions is something "manual testers" have in Postman, it means that you can reuse output from a manual test in the next manual test you execute.. (auth headers, ids, etc..)
This is something that we also need but I don't think so it can be done in the extension itself

- Generating code from OpenAPI definitions, we are doing it already.. it would be a good contribution to the UI

As you see, we have some clear ideas about what we need for our team..

We have been investing and contributing to karate-core, we love free software because it give as the right to help ourselves
And for sure we want the best for karate ecosystem which is where we are living right now...

**Comment by kirksl** [comment]
all good points.

regarding default terminal...
i try to remain neutral.  the reason why we went with cmd as a priority is that we actually saw more people using it instead of powershell.  additionally the command line syntax was more aligned with linux and macOs terminals.  we definitely want to support powershell it was just a much lower priority.  more than happy to support it if you want to add the syntax support for it.

regarding auto-detection...
the reason we did this was to support multiple projects being loaded into the IDE at the same time and to allow the user greatest flexibility.  i would be happy to hear your ideas on how to improve the user experience.

regarding copy/pasting issues...
were you able to solve all of this by fixes to karate-core.  if not what changes are you suggesting to fix this with karate runner extension?  definitely agree with you anything to make vscode equal or better to intellij, webstorm, etc we want to do it to beat them!

regarding executions view...
this seems so similar to "tests" view we already have.  how are you determining pass/failure per test with the green check marks?  we were going to integrate this into the "tests view" with karate team by tracking a real time results file.  perhaps you have a better solution?  in any event i think what you are doing with "executions view" is very similar to "tests view" and only one of them needs to exist for the future.
also re-execution and "status bar > click > results > click to execute again" is another thing to solve for.  seems like your "executions view" would replace that.  

regarding session variables...
it could be done by storing variable data into a memento, etc
https://code.visualstudio.com/api/references/vscode-api#Memento
mementos or another storage mechanism could be tracked in another view automatically too. "sessions view" maybe.


let me know how you plan to proceed.  i do have some free time and i'm happy to help you solve some of this and get a new version fo the extension published.

**Comment by ivangsa** [comment]
ok,

this is work in progress already, we would like to have it done by next month

regarding multiple projects I understand what you mean, it's not one of our biggest priority but will take it into account..

also we'll be using https://prettier.io/ for code formatting I think it would be good in the long run and there will be refactorings and additions, hopefully it will be ok to merge it back..

it will be great if we can join forces and if you can coordinate uploading this to the market place and maybe engage some user to help beta-testing

I will be mostly offline for a couple of weeks now but will keep in touch

Best regards!!

**Comment by kirksl** [comment]
sounds good.  please let me know when you have an update ready and we will make something great happen.  thanks again for the contributions and your strong opinions.

**Comment by ivangsa** [comment]
Hi @kirksl

I have refactored "launch/debug auto-configuration" which may be the bigest breaking change

I have replaced "auto-configuration" and multiple build system (which as somehow complex and ) with a simple yet very flexible "template based command"

this is the default new configuration which favors karate-cli but can be used to build a proper command for any build-system/shell/OS

`java '-Dkarate.env=${karateEnv}' '-Dvscode.port=${vscodePort}' -cp '${classpath}' com.intuit.karate.Main ${karateOptions} '${feature}'`

and this snippet **is all there is** to building the final cli command:

```ts
function getRunCommandLine(feature: string) {
    let vscodePort: string = vscode.workspace.getConfiguration('karateRunner.eventLogsServer').get('port');
    let karateEnv: string = vscode.workspace.getConfiguration('karateRunner.karateCli').get('karateEnv');
    let classpath: string = vscode.workspace.getConfiguration('karateRunner.karateCli').get('classpath');
    let karateOptions: string = vscode.workspace.getConfiguration('karateRunner.karateCli').get('karateOptions');
    let debugCommandTemplate: string = vscode.workspace.getConfiguration('karateRunner.karateCli').get('runCommandTemplate');

    return debugCommandTemplate
        .replace('${vscodePort}', vscodePort)
        .replace('${karateEnv}', karateEnv)
        .replace('${classpath}', classpath)
        .replace('${karateOptions}', karateOptions)
        .replace('${feature}', feature);
}
```

- it works out-of-the-box for bash and powershell so I expect it would be ok for most users and OSes, otherwise it would be just a matter of how quotations are placed

- There is still multimodule capability, if users configure `karateRunner.multimodule.rootModuleMarkerFile` with pom.xml, build.gradle, karate.jar, etc... it will generate/run de command in the proper folder

**Obviously this has removed a lot of code + the code reformatting with prettier makes a very big commit/PR**

**I think if we can agree on this refactoring all the rest would be just simple evolution...**

To test this you will need to build from source both karate-runner-fork and karate-core (latest develop branch) and include this (still quick'n'dirty) `VSCodeRuntimeHook.java`

**Take your time** to evaluate if these will cover every single current and future user... and of course if you are happy with it..

Still very much work in progress, just this screenshot to show how it's going
it probably will take a couple of weeks still

**Best Regards**

![image](https://user-images.githubusercontent.com/1246876/104094547-d6a7f880-5291-11eb-99be-421ac145a9d1.png)

[VSCodeHook.zip](https://github.com/ivangsa/karate-runner-fork/files/5791265/VSCodeHook.zip)

**Comment by kirksl** [comment]
@ivangsa 

thank you for the update.  some feedback below after a cursory review.

issues...
running tests via codelens throws extension error in IDE.
running tests via double arrow in tree view throws extension error in IDE.

questions...
what features require using karate 1.0/latest develop?
will the extension still be usable for users using < karate 1.0 (eg 0.9.6)?
what remaining work do you have left to reach feature complete?
what is your plan with the code within VSCodeRuntimeHook.java/VSCodeHook.java?  great if this was not a requirement for end users to have to implement.
will you be updating the readme.md to show usage specific to your implementation, available template options, etc?

thoughts...
i'd like to avoid shocking existing 1000s of users with many/significant updates at once and rollout features across multiple/smaller releases.
i'd like to ensure backwards compatibility (eg classpaths, reports) for users not immediately upgrading to karate 1.0.  many people don't upgrade right away and i really don't want to break them.
very excited about your interest and ideas and i think we'll be able to agree on many things.  some things i am on the fence with, need to see your full implementation, digest it and think about those things.

**Comment by ivangsa** [comment]
Hi @kirksl 

yes, this will be compatible only with Karate 1.0.0+

Regarding merge these two, I think we have very different coding styles, that alone is a good reason not to merge them...

We are using our fork internally but eventually we may be publishing to marketplace

I already thanked you all the effort you put on this, without your extension on the first place I wouldn't even consider starting this one..

Thanks and best regards.
